### ISSUE TITLE
Input img

### ISSUE THREAD

**Issue by SongYxing** [ameraner/dsen2-cr#15]
Does the input have to be cloudy img and SAR img?
Can I just use a single 3-channel jpg as the input image?

**Comment by ameraner** [comment]
Hi @SongYxing , thank you for your question. The model is designed and has been trained on Sentinel-2 images, which have 13 spectral bands, and it's therefore not possible to use simple RGB images as inputs. In principle you could try to modify the model inputs and re-train it from scratch on your dataset though.

**Comment by SongYxing** [comment]
Thanks for your suggestion
