### ISSUE TITLE
Full list of patches train_val_test_patches.csv inaccessible

### ISSUE THREAD

**Issue by vhchuong1997** [ameraner/dsen2-cr#24]
Hello,
Could you please update the link to the train_val_test_patches.csv file?
Currently, the link to access the CSV file is not available.
Thank you.
![image](https://github.com/ameraner/dsen2-cr/assets/51077545/bb665a3f-6295-451e-b428-558ec39ab500)

**Comment by ameraner** [comment]
I've updated the link, hope it works now :)
