### ISSUE TITLE
Question about dataset import

### ISSUE THREAD

**Issue by sypark531** [ameraner/dsen2-cr#27]
Hi, @ameraner 
I have a small issue about the dataset import, so I would like to ask for your help.
The error below appeared, but it appears that the import was not imported properly.
""
Model compiled successfully!
Getting file lists
Number of train files found:  3
Number of validation files found:  3
Number of test files found:  3
Training model name: DSen2-CR_01
Generator initialized
Generator initialized
Generator initialized
Training starts...

Epoch 1/8
Traceback (most recent call last):
  File "dsen2cr_main.py", line 179, in <module>
    run_dsen2cr(args.predict_file, args.resume_file)
  File "dsen2cr_main.py", line 168, in run_dsen2cr
    input_shape, max_queue_size, use_multi_processing, workers)
  File "/home/soyeon/Others/DSen2-CR-main/Code/dsen2cr_tools.py", line 131, in train_dsen2cr
    workers=workers)
  File "/home/soyeon/DSen2CR/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1296, in fit_generator
    steps_name='steps_per_epoch')
  File "/home/soyeon/DSen2CR/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 301, in model_iteration
    aggregator.finalize()
  File "/home/soyeon/DSen2CR/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 138, in finalize
    raise ValueError('Empty training data.')
ValueError: Empty training data.
""
I completed the composition of the input data as written along ReadMe.
Datasetfilelist.csv was constructed, and three folders named S1, S2, and S2_cloudy were created in the path where the csv file exists. Each image TIFF file is stored in each folder.
![image](https://github.com/user-attachments/assets/a53ca2ba-811f-4aab-86af-8b5e9158948b)
![image](https://github.com/user-attachments/assets/c6f2a873-22c0-44f2-93e5-9fe629ae6ff9)

Example of Datasetfilelist.csv : 1, S1, S2, S2_cloudy, ROIs1970_fall_1_p32.tif

May I know what I missed?

**Comment by lzux** [comment]
What does the first digit "1" mean in the Datasetfilelist.csv example? Is the last “ROIs1970_fall_1_p32.tif” the same file name in three folders? Looking forward to your reply, thank you!

**Comment by sypark531** [comment]
Hi, @lzux 
I followed “The first column of each entry is an integer, where 1 defines a training sample, 2 a validation sample, and 3 a test sample” as written in Usage - Dataset Paths.
And the TIFF files in the S1, S2, and S2_cloudy folders all have the same name.
Thank you,

**Comment by lzux** [comment]
Thank you very much for your reply. In fact, I would like to directly use the model_SARcarl.hdf5 trained by the author. Have you tried it? Do the input s1 and s2 data require consistent spatial resolution and row/column numbers? Should the first column in the CSV file be filled with 2 or 3? Besides path information in dsen2cr_main. py, what else needs to be modified? I am a novice in this field and I suspect that I have missed some important information. Please forgive me.

**Comment by lzux** [comment]
> 嗨，我按照“每个条目的第一列是一个整数，其中 1 定义训练样本，2 定义验证样本，3 定义测试样本”，如使用情况 - 数据集路径中所写。 S1、S2 和 S2_cloudy 文件夹中的 TIFF 文件都具有相同的名称。 谢谢

Thank you very much, I understand now.Besides, is there anything else that needs to be modified in the code besides the path information? Thanks~

**Comment by sypark531** [comment]
Unfortunately, I couldn't find a solution to the problem I raised. I think I prepared the data properly, but I don't know why it says Empty training data.

**Comment by lzux** [comment]
> Thank you for the correct answer @sypark531 ! The inputs should have the same spatial resolution (or at least same sampling distance/pixel size), and same shape, otherwise the network won't work. If you would only like to predict, you can set the the first column to 2 or 3, otherwise you should be good to go!

Thank you very much, I understand now. Besides, is there anything else that needs to be modified in the code besides the path information? Thanks~

**Comment by lzux** [comment]
> Unfortunately, I couldn't find a solution to the problem I raised. I think I prepared the data properly, but I don't know why it says Empty training data.

I'm sorry to hear about the problem you encountered. I am currently trying to learn and use it, and if I have any idea, I will share it with you. I hope you can solve it well.

**Comment by sypark531** [comment]
I solved this problem. If you have the same problem as me, please refer to the link below.
https://github.com/tensorflow/hub/issues/384
Since the problem has been resolved, I will close this issue.
