### ISSUE TITLE
How should data be prepared and placed when directly using the model_SARcarl.hdf5 model?

### ISSUE THREAD

**Issue by lzux** [ameraner/dsen2-cr#28]
When using the model_SARcarl.hdf5 model directly for prediction, does s2_cloudy have to include all 13 bands? Do the sizes of s1 and s2_cloudy also have to be exactly the same? In addition, what format should be set for the names of subfolders and images in the input_data_folder path? Thanks~

**Comment by ameraner** [comment]
Hi @lzux , yes to the first two questions. The folders should be called `s1	s2_cloudFree	s2_cloudy`, basically as defined in your datasetfilelist.csv.
