### ISSUE TITLE
Error message "ConcatOp : Dimensions of inputs should match"

### ISSUE THREAD

**Issue by yongjingmao** [ameraner/dsen2-cr#3]
Hi,

I am trying to use your trained model to do some predictions. I have preprocessed my S1 and S2 images to the same same size as your inputs but still get the error message below. Could you please provide some samples of your datasets for us to understand how to preprocess our own data?

Error message: "tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1,13,128,128] vs. shape[2] = [16,1,128,128]"

BTW, when I select the testing model, do I use the s2_cloudy and s1 images automatically?

Thanks in advance!

**Comment by yongjingmao** [comment]
I think this issue is due to the inconsistent batch_size, which is 16 for model setup and 1 for model prediction.

**Comment by fekenzofugi** [comment]
I'm having the same issue. How did you manage to solve it?
