### ISSUE TITLE
About data split

### ISSUE THREAD

**Issue by lironui** [ameraner/dsen2-cr#4]
Hello,

Could you please tell me the details about the 10 ROIs for validation and 10 ROIs for testing?

Regards.

**Comment by P8H** [comment]
I am interested on this too!
I want to evalute properly the predicted images based on the provided pre-trained model. But for this I would need to know which images are used for training, validation and testing.

**Comment by ameraner** [comment]
Hi both, sorry for the late reply. I have updated the Readme with the according information. Feel free to reopen if you need more information.

**Comment by P8H** [comment]
Hi Andrea, thanks for your response. It looks like you have forgotten to make the link to the dataset split public accessible. I getting a message that I have no rights to access the file.

**Comment by ameraner** [comment]
Indeed, fixed now, thank you!

**Comment by P8H** [comment]
Thanks! I have the file list now but the filenames are not in the same format as the referenced dataset.

Datesetfilelist format: "ROIs1158_spring_101_0.tif"
Dataset format: "ROIs1970_fall_93_p128.tif"

I tried to _translate_ the filenames but without success. Could you give a hint, how the previous filenames can be converted such as it matches with the files in the referenced dataset? If this is even possible?

**Comment by ameraner** [comment]
Good question, maybe @PatrickTUM can help with this?

**Comment by P8H** [comment]
It looks like the split in datasetfilelist.csv was done by the "scene_id"? All parts of one scene should be in the same set.

It is safe to assume that the "scene_id" in the datasetfilelist.csv is the same as in the referenced dataset?
Therefor it would be possible to ignore the part_id.

My understading of the naming format: "ROIs1158_spring_<scene_id>_<part_id>.tif"

**Comment by PatrickTUM** [comment]
Hi @lironui & @P8H,

the test split ROI of SEN12MS-CR are as follows:

> 
> 'ROIs1158_spring_106',
> 'ROIs1158_spring_123',
> 'ROIs1158_spring_140',
> 'ROIs1158_spring_31',
> 'ROIs1158_spring_44',
> 'ROIs1868_summer_119',
> 'ROIs1868_summer_73',
> 'ROIs1970_fall_139',
> 'ROIs2017_winter_108',
> 'ROIs2017_winter_63'

You can find the patch-wise information of splits [here](https://syncandshare.lrz.de/getlink/fiX8Gv8SKQS8QMZrtXWZi5Rr/supplementary_SEN12MSCR). The validation split is just a suggestion, and may be adapted to your preferences. Note that the data set released is not identical to the one used in [1], and so the splits aren't exactly identical either. The collected ROI of SEN12MS-CR are a subset of those of [2], and to make it directly comparable to [2] (i.e. to establish pixel-wise correspondences), we applied an additional CRS transform in [3]. This transform, however, was not included in the earlier version of the data set. You can find additional informations wrt the changes in [3].

Hoping this helps!
Cheers

[1] Meraner, A., Ebel, P., Zhu, X. X., & Schmitt, M. (2020). Cloud removal in Sentinel-2 imagery using a deep residual neural network and SAR-optical data fusion. ISPRS Journal of Photogrammetry and Remote Sensing, 166, 333-346.
[2] Schmitt, Michael, et al. "SEN12MS--A Curated Dataset of Georeferenced Multi-Spectral Sentinel-1/2 Imagery for Deep Learning and Data Fusion." arXiv preprint arXiv:1906.07789 (2019).
[3] Ebel, P., Meraner, A., Schmitt, M., & Zhu, X. X. (2020). Multisensor data fusion for cloud removal in global and all-season Sentinel-2 imagery. IEEE Transactions on Geoscience and Remote Sensing.

**Comment by P8H** [comment]
Indeed, that helps!
Thanks a lot @PatrickTUM and @ameraner!
