### ISSUE TITLE
Some strange phenomena about the intputpred picture

### ISSUE THREAD

**Issue by maxpluspro** [ameraner/dsen2-cr#8]
I downloaded a small part of the SEN12MS-CR dataset for experiments.For example, the file names in the three folders (s1, s2_cloudFree, s2_cloudy) are ROIs1158_spring_s1_1_p30.tif, ROIs1158_spring_s2_1_p30.tif, ROIs1158_spring_s2_cloudy_1_p30.tif.
Then, for convenience, I rename the files in each folder to 1.tiff, 2.tiff, 3.tiff.... The corresponding datasetfilelist.csv has also been changed.
  But the final cloud removal prediction picture inputred.png is strange. It can achieve the effect of cloud removal, but it looks like the enlargement of an area of inputtarg.png (groundtruth). The features of inputred.png and inputtarg.png (groundtruth) do not correspond. As shown in the picture below.
  I don't know where my problem is. I think it is in the data file reading, but I don't understand. Has anyone ever had a similar problem? What should I do to get real results? thank you.
![dsen](https://user-images.githubusercontent.com/93385379/196381332-b00f60f8-92bd-4bec-8c02-504c14614ea9.png)

**Comment by ameraner** [comment]
Hi @maxpluspro, thanks for the issue!
Did you try to adapt the `crop_size` parameter at prediction time? See here https://github.com/ameraner/dsen2-cr/blob/59e81ae0d013bcae992d078e92a1175cc4cbf257/Code/dsen2cr_main.py#L52 
It might be that you're still cropping the images as during the training step, hence the output is smaller... if you use the same size of your input image, it might work as you are expecting.

Regarding the comment that the features between the groud-truth and prediction don't match... I don't really agree, seems like the network is doing an ok job within the expected performance.... particularly considering the strange shapes present in the scene (I'm not even really sure what those yellow-ish areas are... erosion/deforestation?).
